services:
  mongodb:
    hostname: mongodb
    # image: mongodb/mongodb-community-server:6.0-ubi8 
    image: mongo:7.0.12
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:supersecret@localhost:27017/ --quiet
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=supersecret
    volumes:
      - ./.data/mongodb_storage:/data/db
      - ./.data/mongodb_configdb:/data/configdb
    networks: 
      - arxivrag_network   

  mongo-express:
    hostname: mongo-express
    image: mongo-express
    ports:
      - 8091:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=supersecret
      - ME_CONFIG_MONGODB_URL=mongodb://admin:supersecret@mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy

    networks: 
      - arxivrag_network 

networks:
  arxivrag_network:
    name: arxivrag_network
    external: true