services:
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    command: server --console-address ":9001" /data
    ports:
      - 9800:9000
      - 9801:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./.data:/data
    networks:
      - arxivrag_network

networks:
  arxivrag_network:
    name: arxivrag_network
    external: true
      