services:
  ollama1:
    image: ollama/ollama:0.3.6
    ports:
      - 11434:11434
    volumes:
      - ./.data:/root/.ollama
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
    