services:
  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    networks: 
      - arxivrag_network 

networks:
  arxivrag_network:
    name: arxivrag_network
    external: true
