services:
  arvixrag_minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - ./.storage/minio_storage:/data
    networks:
      - arvixrag_network

networks:
  arvixrag_network:
    name: arvixrag_network
    external: true
      